---
title: "Evaluation"
---

## Elements

| Component | Description                                  | Points |
|-----------|----------------------------------------------|--------:|
| Exams     |There will be three (3) in-class examinations, plus a final held during the exam period that is partially cumulative. Each exam is worth 40 points. The top 3 of 4 exam scores will count toward your final grade. You may choose not to take the final. | 120 |
| Quizzes | There will be four (4) in-class quizzes. Each quiz is worth 10 points. The top 3 of 4 quiz scores will count toward your final grade. | 30 |
| Participation | There are a total of 15 points available by completing **EITHER** a paper or blog assignment. | 15 |
|  |   *Blog*: You are encouraged to create and maintain a neuroscience-related blog on PSU’s blog server, <http://sites.psu.edu>. You may create up to 3 posts and earn 5 points/post, for a total of 15 possible points. [Assignment](https://assignments/blog-assignment.md) | |
| |  *Paper*: You may write a 3-5 pp (double-spaced) news-style paper on a topic related to biological psychology. The paper is worth 15 points. [Assignment](assignments/paper-assignment.md)| |
| | **TOTAL POINTS POSSIBLE** | 165 |
| Extra Credit | There may be extra credit opportunities provided at random and unannounced times during the semester. Come to class in order to benefit from them.| |

[Data about recent performance in previous years](grades/analysis.pdf)

### Grading Scheme

| Points  | Percent | Grade |
|---------|---------|-------|
| 165+    | 100+    | A+    |
| 155-164 | 94-99   | A     |
| 148-154 | 90-93   | A-    |
| 143-147 | 87-89   | B+    |
| 139-142 | 84-86   | B     |
| 132-138 | 80-83   | B-    |
| 127-131 | 77-79   | C+    |
| 115-126 | 70-76   | C     |
| 99-114  | 60-69   | D     |
| 0-98    | <59     | F     |
