---
title: "Grades"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
```

```{r create-eval-processing-function, include=FALSE}
Process.exam.quiz <- function(canvas.fn, eq.name="quiz1", pts.poss=10) {
  # Takes a raw Canvas-format .csv file and processes it.
  
  stopifnot(file.exists(canvas.fn))
  if (pts.poss < 0) {
    stop("Must specify pts.poss.")
  }
  
  eq <- read.csv(canvas.fn, skip = 2, header = FALSE)
  names(eq) <- c("student", "id", "email", "section", "points")
  
  pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 150)
  grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
  quiz.1$grade <- cut(x = eq$points, 
                      breaks = pts.poss*pct/100, 
                      labels = grades, 
                      right = FALSE)
  eq$eval <- "quiz1"
  eq$pts.poss <- pts.poss
  
  eq
}
```


## [Quiz 1](quiz/psych-260-quiz-1-ans.pdf)

```{r quiz-1-files, include=FALSE}
quiz.1 <- read.csv(file = "grades/csv/Canvas Report - Exam 6928 - Section17621.csv", skip = 2, header=FALSE)
names(quiz.1) <- c("student", "id", "email", "section", "points")

pts.poss = 10
pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 150)
grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
quiz.1$grade <- cut(x = quiz.1$points, 
                    breaks = pts.poss*pct/100, 
                    labels = grades, 
                    right = FALSE)
quiz.1$eval <- "quiz1"
quiz.1$pts.poss <- pts.poss
```

```{r quiz-1 histogram, message=FALSE, echo=FALSE}
quiz.1 %>%
  ggplot() +
  geom_histogram(mapping = aes(x=points, fill=grade))
```

## [Exam 1](exam/psych-260-exam-1-ans.pdf)

```{r import-exam-1, include=FALSE}
exam.1 <- read.csv(file = "grades/csv/Canvas Report - Exam 7116 - Section17621.csv", skip = 2, header=FALSE)
names(exam.1) <- c("student", "id", "email", "section", "points")

pts.poss = 40
pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 120)
grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
exam.1$grade <- cut(x = exam.1$points, 
                    breaks = pts.poss*pct/100, 
                    labels = grades, 
                    right = FALSE)
exam.1$eval <- "exam1"
exam.1$pts.poss <- pts.poss
```

```{r exam-1 histogram, message=FALSE, echo=FALSE}
exam.1 %>%
  ggplot() +
  geom_histogram(mapping = aes(x=points, fill=grade))
```

## [Quiz 2](quiz/psych-260-quiz-2-ans.pdf)

```{r quiz-2-files, include=FALSE}
quiz.2 <- read.csv(file = "grades/csv/Canvas Report - Exam 7277 - Section17621.csv", skip = 2, header=FALSE)
names(quiz.2) <- c("student", "id", "email", "section", "points")

pts.poss = 10
pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 150)
grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
quiz.2$grade <- cut(x = quiz.2$points, 
                    breaks = pts.poss*pct/100, 
                    labels = grades, 
                    right = FALSE)
quiz.2$eval <- "quiz2"
quiz.2$pts.poss <- pts.poss
```

```{r quiz-2 histogram, message=FALSE, echo=FALSE}
quiz.2 %>%
  ggplot() +
  geom_histogram(mapping = aes(x=points, fill=grade))
```

## [Exam 2](exam/psych-260-exam-2-ans.pdf)

```{r import-exam-2, include=FALSE}
exam.2 <- read.csv(file = "grades/csv/Canvas Report - Exam 7418 - Section17621.csv", skip = 2, header=FALSE)
names(exam.2) <- c("student", "id", "email", "section", "points")

pts.poss = 40
pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 120)
grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
exam.2$grade <- cut(x = exam.2$points, 
                    breaks = pts.poss*pct/100, 
                    labels = grades, 
                    right = FALSE)
exam.2$eval <- "exam2"
exam.2$pts.poss <- pts.poss
```

```{r exam-2 histogram, message=FALSE, echo=FALSE}
exam.2 %>%
  ggplot() +
  geom_histogram(mapping = aes(x=points, fill=grade))
```

## [Quiz 3](quiz/psych-260-quiz-3-ans.pdf)

```{r quiz-3-files, include=FALSE}
quiz.3 <- read.csv(file = "grades/csv/Canvas Report - Exam 7651 - Section17621.csv", skip = 2, header=FALSE)
names(quiz.3) <- c("student", "id", "email", "section", "points")

pts.poss = 10
pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 150)
grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
quiz.3$grade <- cut(x = quiz.3$points, 
                    breaks = pts.poss*pct/100, 
                    labels = grades, 
                    right = FALSE)
quiz.3$eval <- "quiz2"
quiz.3$pts.poss <- pts.poss
```

```{r quiz-3-histogram, message=FALSE, echo=FALSE}
quiz.3 %>%
  ggplot() +
  geom_histogram(mapping = aes(x=points, fill=grade))
```

## [Exam 3](exam/psych-260-exam-3-ans.pdf)

```{r exam-3-files, include=FALSE}
exam.3 <- read.csv(file = "grades/csv/Canvas Report - Exam 7889 - Section17621.csv", skip = 2, header=FALSE)
names(exam.3) <- c("student", "id", "email", "section", "points")

pts.poss = 40
pct <- c(0, 60, 70, 77, 80, 84, 87, 90, 94, 150)
grades <- c("F", "D", "C","C+", "B-", "B", "B+", "A-", "A")
exam.3$grade <- cut(x = exam.3$points, 
                    breaks = pts.poss*pct/100, 
                    labels = grades, 
                    right = FALSE)
exam.3$eval <- "exam3"
exam.3$pts.poss <- pts.poss
```

```{r exam-3-histogram, message=FALSE, echo=FALSE}
exam.3 %>%
  ggplot() +
  geom_histogram(mapping = aes(x=points, fill=grade))
```


<!--- Create combined grade file. -->

```{r combined-grade-file, echo=FALSE}
grades.merged <- rbind(quiz.1, quiz.2, exam.1, exam.2, quiz.3, exam.3)

grades.merged %>%
  select(student, id, eval, eval, grade, points, pts.poss) %>%
  group_by(student, id) %>%
  mutate(tot.pts = sum(points),
         n.evals = n(),
         tot.poss = sum(pts.poss),
         pct.pts = 100*tot.pts/tot.poss) ->
  grades.merged
write.csv(x = grades.merged, file = "grades/csv/grades.merged.csv", row.names = FALSE)
```
