---
title: "Policies & Values"
---

### Academic Integrity

Penn State defines academic integrity as the pursuit of scholarly activity in an open, honest and responsible manner. All students should act with personal integrity, respect others dignity, rights and property, and help create and maintain an environment in which all can succeed through the fruits of their efforts (Faculty Senate Policy 49-20). Sanctions for academic misconduct can include a grade of F for the course as well as other penalties.

Students are responsible for maintaining academic integrity.  Violations include cheating on exams, talking to others during exams, looking at another student's test materials or answers during an exam, removing exams from the classroom without consent from the instructor, plagiarizing (do not copy from someone else!), and dishonesty in any aspect of course participation.

When you complete assignments, remember the **ABC**s to avoid plagiarism: **A**lways place copied information within quotation marks, include information about the quoted or paraphrased source in a **B**ibliography, and **C**ite the source in the body (in the text) of your paper immediately after the quoted or paraphrased information. When in doubt, cite in the text and include the source in a bibliography.

### Late, missed or make-up assignments

#### Exams

Make-up exams may be permitted under unusual circumstances such as (a) an interview for graduate school or a job, (b) illness, (c) religious observance, (d) the death of a family member, or (e) any other event recognized by the university as a valid excuse for absence from class.

If you must miss class on the day an exam is scheduled, you must do the following:

1. Contact the TA or the instructor by telephone, email, or in person in advance of the exam. Twenty-four hours notice is expected. If you do not contact the TA or instructor in advance, it is possible that you may not be able to schedule a make-up exam.
2. Arrange with the TA or instructor to take a make-up exam as soon as possible, but no later than one (1) week following the date of the scheduled exam. It is your responsibility, not the TA's or the instructor's to schedule an approved make-up exam in a timely way.

#### Quizzes

No make-up quizzes will be given except under unusual circumstances. You may ask for a copy of the quiz for studying purposes, however.

#### Accommodation for persons with disabilities

Penn State welcomes students with disabilities into the University's educational programs. Please refer to the information provided by Student Disability Resources (SDR) at <http://equity.psu.edu/student-disability-resources/> for information about the procedures required to obtain reasonable accommodations in this course. Students should discussSDR-approved accommodations with their instructor as early in the semester as possible, even if they have taken another course with the instructor. Please note: students are not required to provide their instructor with information about the nature of their condition.
 
Penn State students are also welcome to contact other units for assistance with personal concerns that interfere with academic progress, including: Counseling and Psychological Services (CAPS; <http://studentaffairs.psu.edu/counseling/>), the Office of Student Affairs (<http://studentaffairs.psu.edu/>), Career Services (<http://studentaffairs.psu.edu/career/>), the Center for Women Students (<http://studentaffairs.psu.edu/womenscenter/>), the LGBTQA Student Resource Center (<http://studentaffairs.psu.edu/lgbtqa/>), the Office of Sexual Misconduct
Prevention and Response (<http://titleix.psu.edu/>), Penn State Educational Equity (<http://equity.psu.edu/>), the Multicultural Resource Center (<http://equity.psu.edu/mrc>), and University 
Health Services (<http://studentaffairs.psu.edu/health/>).

### Nondiscrimination Statement

The Pennsylvania State University is committed to equal access to programs, facilities, admission and employment for all persons. It is the policy of the University to maintain an environment free of harassment and free of discrimination against any person because of age, race, color, ancestry, national origin, religion, creed, service in the uniformed services (as defined in state and federal law), veteran status, sex, sexual orientation, marital or family status, pregnancy, pregnancy-related conditions, physical or mental disability, gender, perceived gender, gender identity, genetic information or political ideas.  Discriminatory conduct and harassment, as well as sexual misconduct and relationship violence, violates the dignity of individuals, impedes the realization of the University's educational mission, and will not be tolerated.
 
Direct all inquiries regarding the nondiscrimination policy to:
 
Dr. Kenneth Lehrman III</br>
Vice Provost for Affirmative Action</br>
Affirmative Action Office</br>
The Pennsylvania State University</br>
328 Boucke Building</br>
University Park, PA 16802-5901</br>
Email: kfl2@psu.edu</br>
Tel (814) 863-0471

### Diversity Statement

This classroom is a place where you will be treated with respect. All members of this class are expected to contribute to a respectful, welcoming and inclusive environment for every other member of the class.  Penn State is committed to creating an educational environment which is free from intolerance directed toward individuals or groups and strives to create and maintain an environment that fosters respect for others as stated in Policy AD29 Statement on Intolerance.
 
### Mandated Reporting Statement

Penn State's policies require me, as a faculty member, to share information about incidents of sex-based discrimination and harassment (discrimination, harassment, sexual harassment, sexual misconduct, dating violence, domestic violence, stalking, and retaliation) with Penn State's Title IX coordinator or deputy coordinators, regardless of whether the incidents are stated to me in person or shared by students as part of their coursework. For more information regarding the University's policies and procedures for responding to reports of sexual or gender-based harassment or misconduct, please visit <http://titleix.psu.edu>.
 
Additionally, I am required to make a report on any reasonable suspicion of child abuse in accordance with the Pennsylvania Child Protective Services Law.

### Penn State Principles

The Pennsylvania State University is a community dedicated to personal and academic excellence. The Penn State Principles were developed to embody the values that we hope our students, faculty, staff, administration, and alumni possess. At the same time, the University is strongly committed to freedom of expression. Consequently, these Principles do not constitute University policy and are not intended to interfere in any way with an individual's academic or personal freedoms. We hope, however, that individuals will voluntarily endorse these common principles, thereby contributing to the traditions and scholarly heritage left by those who preceded them, and will thus
leave Penn State a better place for those who follow.
 
**I will respect the dignity of all individuals within the Penn State community**. The University is committed to creating and maintaining an educational environment that
respects the right of all individuals to participate fully in the community. Actions motivated by hate, prejudice, or intolerance violate this principle. I will not engage in any behaviors that compromise or demean the dignity of individuals or groups, including intimidation, stalking, harassment, discrimination, taunting, ridiculing, insulting, or acts of violence. I will demonstrate respect for others by striving to learn from differences between people, ideas, and opinions and by avoiding behaviors that inhibit the ability of other community members to feel safe or welcome as they pursue their academic goals.
 
**I will practice academic integrity**. Academic integrity is a basic guiding principle for all academic activity at Penn State University, allowing the pursuit of scholarly activity in an open, honest, and responsible manner. In accordance with the University Code of Conduct, I will practice integrity in regard to all academic assignments. I will not engage in or tolerate acts of falsification, misrepresentation or deception because such acts of dishonesty violate the fundamental ethical principles of the University 
community and compromise the worth of work completed by others.
 
**I will demonstrate social and personal responsibility**. The University is a community that promotes learning; any behaviors that are inconsistent with that goal are
unacceptable. Irresponsible behaviors, including alcohol or drug abuse and the use of violence against people or property, undermine the educational climate by 
threatening the physical and mental health of members of the community. I will exercise personal responsibility for my actions and I will make sure that my actions do not 
interfere with the academic and social environment of the University. I will maintain a high standard of behavior by adhering to the Code of Conduct and respecting the 
rights of others.
 
**I will be responsible for my own academic progress and agree to comply with all University policies**. The University allows students to identify and achieve their academic goals by providing the information needed to plan the chosen program of study and the necessary educational opportunities, but students assume final responsibility for course scheduling, program planning, and the successful completion of graduation requirements. I will be responsible for seeking the academic and career information 
needed to meet my educational goals by becoming knowledgeable about the relevant policies, procedures, and rules of the University and academic program, by consulting 
and meeting with my adviser, and by successfully completing all of the requirements for graduation.
 
### Penn State Values

[**Integrity**](http://universityethics.psu.edu/examples-action#integrityexamples): We act with integrity and honesty in accordance with the highest academic, professional, and ethical standards.
 
[**Respect**](http://universityethics.psu.edu/examples-action#respectexamples): We respect and honor the dignity of each person, embrace civil discourse, and foster a diverse and inclusive community.
 
[**Responsibility**](http://universityethics.psu.edu/examples-action#responsibilityexamples): We act responsibly, and we are accountable for our decisions, actions, and their consequences.
 
[**Discovery**](http://universityethics.psu.edu/examples-action#discoveryexamples): We seek and create new knowledge and understanding, and foster creativity and innovation, for the benefit of our communities, society, and the environment.
 
[**Excellence**](http://universityethics.psu.edu/examples-action#excellenceexamples): We strive for excellence in all our endeavors as individuals, an institution, and a leader in higher education.
 
[**Community**](http://universityethics.psu.edu/examples-action#communityexamples): We work together for the betterment of our University, the communities we serve, and the world.