---
title: "Schedule"
---

## Week 1, January 9-13

### Mon, Jan 9

- Introduction to the course
- What is a system?
- Assignment
    - Read W&B 1:2-19.
    - Review <https://en.wikipedia.org/wiki/Systems_theory>
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-09.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-09.md)
    - [PDF](lecture-notes/260-2017-01-09.pdf)

### Wed, Jan 11

- History of neuroscience
- Assignments
    - Review <http://www.columbia.edu/cu/psychology/courses/1010/mangels/neuro/history/history.html>.
   - Scan: <https://faculty.washington.edu/chudler/hist.html>
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-11.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-11.md)
    - [PDF](lecture-notes/260-2017-01-11.pdf)

### Fri, Jan 13

- Levels of analysis; neuroscience methods I
- Assignments
    - Read: W&B 2:24, 26, 44-49, 3:53, 70-76.
    - Watch: [Beautiful 3-D Brain Scans Show Every Synapse](https://youtu.be/nvXuq9jRWKE)
    - Optional
        - [Grillner, Kozlov, Kotaleski (2005)](http://www.ncbi.nlm.nih.gov/pubmed/16146688).
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-13.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-13.md)
    - [PDF](lecture-notes/260-2017-01-13.pdf)

## Week 2, January 16-20

### Mon, January 16

**NO CLASS MEETING**

### Wed, January 18

- Neuroscience methods II.
- Assignment
    - Watch: [Magnetic Resonance Imaging Explained](https://youtu.be/MiL0wCZr0Mw)
    - Optional: <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>.
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-18.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-18.md)
    - [PDF](lecture-notes/260-2017-01-18.pdf)

### Fri, January 20

- Topic
    - Neuroanatomy I.
- Assignment
    - Read W&B: 2:30-43.
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-20.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-20.md)
    - [PDF](lecture-notes/260-2017-01-20.pdf)

## Week 3, January 23-27

### Mon, January 23

- A-L: Tour of [Social, Life, & Engineering Sciences Imaging Center (SLEIC)](http://imaging.psu.edu). Meet in lobby of  [Chandlee](http://www.registrar.psu.edu/soc_maps/chandlee.html).
- M-Z: Neuroanatomy Lab. 
    - Handout: [PDF](assignments/neuroanatomy-lab-handout.pdf). [HTML](assignments/neuroanatomy-lab-handout.html). [docx](assignments/neuroanatomy-lab-handout.docx). [Markdown](assignments/neuroanatomy-lab-handout.md)

### Wed, January 25

- A-L: Neuroanatomy Lab 
    - Handout: [PDF](assignments/neuroanatomy-lab-handout.pdf). [HTML](assignments/neuroanatomy-lab-handout.html). [docx](assignments/neuroanatomy-lab-handout.docx). [Markdown](assignments/neuroanatomy-lab-handout.md)
- M-Z: Tour of [Social, Life, & Engineering Sciences Imaging Center (SLEIC)](http://imaging.psu.edu). Meet in lobby of  [Chandlee](http://www.registrar.psu.edu/soc_maps/chandlee.html).

### Fri, January 27

- Topic
    - Neuroanatomy II.
    - **Quiz 1**. [Answer Key](quiz/psych-260-quiz-1-ans.pdf). [Score histogram](grades.html#quiz-1)
- Assignment
    - Read W&B: 2:30-43.
    - Read W&B: 2:20-29.
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-20.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-20.md)
    - [PDF](lecture-notes/260-2017-01-20.pdf)

## Week 4, January 30 - February 3
<!-- Einat out this week -->
### Mon, January 30

- Topics
    + Neuroanatomy III
- Lecture notes
    - [HTML](lecture-notes/260-2017-01-30.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-01-30.md)
    - [PDF](lecture-notes/260-2017-01-30.pdf)

### Wed, February 1

- Topics
    - Cells of the nervous system.
    - Neurophysiology I
- Assignment
    - Read W&B: 2:20-29.
    - Read W&B 3:50-55.
- Lecture notes
    - [HTML](lecture-notes/260-2017-02-01.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-01.md)
    - [PDF](lecture-notes/260-2017-02-01.pdf)
    
### Fri, February 3

- Topic
    - Neurophysiology II.
- Assignment
    - Read W&B 3:55-59.
    - Watch <https://www.youtube.com/embed/PtKAeihnbv0>
- Lecture notes
    - [HTML](lecture-notes/260-2017-02-03.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-03.md)
    - [PDF](lecture-notes/260-2017-02-03.pdf)

## Week 5, February 6-10

### Mon, February 6

- Topic
    - Neurophysiology III
    - Exam 1 review
- Assignment
    - Read W&B 3:59-69
- Lecture notes
    - [HTML](lecture-notes/260-2017-02-06.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-06.md)
    - [PDF](lecture-notes/260-2017-02-06.pdf)
- Exam 1 Study Guide
    - [HTML](lecture-notes/exam-1-study-guide.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/exam-1-study-guide.md)
    - [PDF](lecture-notes/exam-1-study-guide.pdf)

### Wed, February 8

- **Exam 1**. [Answer Key](exam/psych-260-exam-1-ans.pdf). [Score Distribution](grades.html#exam-1)

### Fri, February 10

- Neurophysiology IV
- Lecture notes
    - [HTML](lecture-notes/260-2017-02-10.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-10.md)
    - [PDF](lecture-notes/260-2017-02-10.pdf)

## Week 06, February 13-17

### Mon, February 13

- Neurochemistry I.
- Assignment
    -  Read W&B 4:82-86.
    - [HTML](lecture-notes/260-2017-02-13.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-13.md)
    - [PDF](lecture-notes/260-2017-02-13.pdf)

### Wed, February 15

- Neurochemistry II.
- Assignment
    -  Read W&B 4:82-86.
    - [HTML](lecture-notes/260-2017-02-15.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-15.md)
    - [PDF](lecture-notes/260-2017-02-15.pdf)

### Fri, February 17

- **Quiz 2**. [Answer Key](quiz/psych-260-quiz-2-ans.pdf). [Score histogram](grades.html#quiz-2)
- Exam 1 returned. [Answer key](exam/psych-260-exam-1-ans.pdf). [Score histogram](grades.html#exam-1).
    - [HTML](lecture-notes/260-2017-02-17.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-17.md)
    - [PDF](lecture-notes/260-2017-02-17.pdf)

## Week 07, February 20-24

### Mon, February 20

- Hormones and the brain
- Assignment
    - Read W&B 8:208-226
    - [HTML](lecture-notes/260-2017-02-20.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-20.md)
    - [PDF](lecture-notes/260-2017-02-20.pdf)

### Wed, February 22

- Your brain on sex
- Assignment
    - Read W&B 8:226-253
    - [HTML](lecture-notes/260-2017-02-22-sex.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-22-sex.md)
    - [PDF](lecture-notes/260-2017-02-22-sex.pdf)

### Fri, February 24
<!-- Einat out. -->
- Biological rhythms and sleep
- Assignment
    - Read W&B 10:278-308.
    - **1st blog post due**.
    - [HTML](lecture-notes/260-2017-02-24-sleep.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-02-24-sleep.md)
    - [PDF](lecture-notes/260-2017-02-24-sleep.pdf)
    
## Week 8, February 27 - March 3

### Mon, February 27
<!-- Rick to Temple -->
- Exam 2 Study Guide
    - [HTML](lecture-notes/exam-2-study-guide.html)

### Wed, March 1

- **Exam  2**. [Answer Key](exam/psych-260-exam-2-ans.pdf). [Score histogram](grades.html#exam-2)

### Fri, March 3

- Evolution and development of the human brain.
- Assignment
    - Read [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015).
    - [HTML](lecture-notes/260-2017-03-03-evo-devo.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-03-evo-devo.md)

## Spring Break, March 6 - 10

**NO CLASSES**

## Week 9, March 13-17

### Mon, March 13

- Psychopathology I: Schizophrenia.
- Assignment
    - Read W&B 12:338-352.
    - [HTML](lecture-notes/260-2017-03-13-schizophrenia.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-13-schizophrenia.md)
    - [PDF](lecture-notes/260-2017-03-13-schizophrenia.pdf)

### Wed, March 15

- Psychopathology II: Bipolar disorder.
- Assignment
    - Read W&B 12:358-359.
    - [HTML](lecture-notes/260-2017-03-15-bipolar.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-15-bipolar.md)
    - [PDF](lecture-notes/260-2017-03-15-bipolar.pdf)

### Fri, March 17

- Psychopathology III: Depression.
- Assignment
    - Read W&B 12:352-358.
    - [HTML](lecture-notes/260-2017-03-17-depression.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-17-depression.md)
    - [PDF](lecture-notes/260-2017-03-17-depression.pdf)

## Week 10, March 20-24

#### Mon, March 20

- Emotion, Happiness, Reward
- Assignment
    - Read W&B 11:310-336.
    - [HTML](lecture-notes/260-2017-03-20-reward.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-20-reward.md)
    - [PDF](lecture-notes/260-2017-03-20-reward.pdf)

### Wed, March 22
<!-- Rick definitely away -->
- Fear and Stress.
- Assignment
    - [HTML](lecture-notes/260-2017-03-22-fear.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-22-fear.md)
    - [PDF](lecture-notes/260-2017-03-22-fear.pdf)

### Fri, March 24
<!-- Rick definitely away -->
- **Quiz 3**. [Answer Key](quiz/psych-260-quiz-3-ans.pdf). [Score histogram](grades.html#quiz-3)
- Exam 2 returned.

## Week 11, March 27-31 

### Mon, March 27

- Sensory systems.
- Assignment
    - Read W&B 5:110-121
- Assignment
    - [HTML](lecture-notes/260-2017-03-27-sensation.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-27-sensation.md)
    - [PDF](lecture-notes/260-2017-03-27-sensation.pdf)

### Wed, March 29

- Somatosensation
- Assignment
    - Read W&B 5:121-126; 6:162-164
    - [HTML](lecture-notes/260-2017-03-29-somatosensation.html)
    - [Markdown](https://github.com/psu-psychology/psych-260-spring-2017/tree/master/lecture-notes/260-2017-03-29-somatosensation.md)
    - [PDF](lecture-notes/260-2017-03-29-somatosensation.pdf)

### Fri, March 31

- Action
- Assignment
    - Read W&B 5:126-143
    - **Blog post #2 (of 3) due**
    
## Week 12, April 3-7

### Mon, April 3

- Action II

### Wed, April 5
<!--- Rick at SRCD -->
- Exam 3 review
    
### Fri, April 7
<!--- Rick at SRCD -->
- **Exam 3**

## Week 13, April 10-14

### Mon, April 10

- Audition
- Assignment
    - Read W&B 6:144-162

### Wed, April 12

- Vision I.
- Assignment
    - Read W&B 7:174-185.

### Fri, April 14

- Vision II.
- Assignment
    - Read W&B 7:185-207.

## Week 14, April 17-21

### Mon, April 17

- **Quiz 4**
- Exam 3 returned.
- **Papers or blog post #3 (of 3) due**

### Wed, April 19

- Learning & memory.
- Assignment
    - Read 13:368-383

### Fri, April 21

- Learning & memory II.
- Assignment
    - Read 13:368-383-393

## Week 15, April 24-28

### Mon, April 24

- Speed of nervous system conduction lab
   
### Wed, April 26

- Review for Exam 4.

### Fri, April 28

- The Cerebral Symphony
    
## Week 16, May 1-5

### TBA

- **Exam 4**
