---
title: "News"
---

### Neuroscience in the news

Neuroscience is a rapidly developing field. I will post neuroscience-related news items here from time to time.

- What Happened Within This Player's Skull. <http://www.nytimes.com/interactive/2017/01/09/sports/football/what-happened-within-this-players-skull-football-concussions.html?_r=0>. #concussion

- Kim, A. J., Fenk, L. M., Lyu, C., & Maimon, G. (2017). Quantitative Predictions Orchestrate Visual Signaling in Drosophila. Cell, 0(0). <https://doi.org/10.1016/j.cell.2016.12.005>. #perception

- Gomez, J., Barnett, M. A., Natu, V., Mezer, A., Palomero-Gallagher, N., Weiner, K. S., … Grill-Spector, K. (2017). Microstructural proliferation in human cortex is coupled with the development of face processing. Science, 355(6320), 68–71. <https://doi.org/10.1126/science.aag0311>. [NPR story](http://www.npr.org/sections/health-shots/2017/01/05/508237061/brain-area-that-recognizes-faces-gets-bigger-and-better-in-young-adults) #adolescence #structuralMRI

- Westlye, L. T., Kaufmann, T., Alnæs, D., Hullstein, I. R., & Bjørnebekk, A. (2017). Brain connectivity aberrations in anabolic-androgenic steroid users. NeuroImage: Clinical, 13, 62–69. <https://doi.org/10.1016/j.nicl.2016.11.014>. #connectivity

- Meyniel, F., Goodwin, G. M., Deakin, J. W., Klinge, C., MacFadyen, C., Milligan, H., … Gaillard, R. (2016). A specific role for serotonin in overcoming effort cost. eLife, 5, e17282. <https://doi.org/10.7554/eLife.17282>. #reward

- Seelye, K. Q. (2016, December 31). Kitty Dukakis, a Beneficiary of Electroshock Therapy, Emerges as Its Evangelist. The New York Times. Retrieved from <http://www.nytimes.com/2016/12/31/us/kitty-dukakis-electroshock-therapy-evangelist.html>. #depression #ect

### Neuro talks @ PSU

This is a list of talks that students may wish to attend. *Attendance is not required, however*. Reports on the talks could serve as the basis of one or more blog posts or a paper.

#### Dr. Nadav Ahituv, Wednesday, January 11, 2017, 4 PM, 108 Wartik Lab

"Functional Characterization of Gene Regulatory Elements"

#### Dr. Claire Cheetham, January 12, 2017, 4 PM, 008 Mueller

Dr. Cheetham’s research aims to elucidate the mechanisms through which neurons form and maintain precise connections. She approaches the question using the mouse olfactory bulb system, which is experimentally accessible in vivo and undergoes adult neurogenesis. She uses a combination of optogenetics, electrophysiology and behavior to study how new neurons are integrated into functional circuits. She has made important contributions to our understanding of synapse formation and maturation in both cortex and the olfactory bulb. She earned her PhD with Dr. Gerald Finnerty at University College London where she showed that a critical period for map reorganization in the visual cortex corresponded to presynaptic maturation. She then moved to NIH to work with Dr. Leo Belluscio where she developed her current model system. She is currently an independently-funded Research Assistant Professor at Carnegie Mellon.
 
#### Dr. Rachel Roberts-Galbraith, January 17, 2017, 4 PM, 008 Mueller

Dr. Roberts-Galbraith uses planarians as a model organism to study brain regeneration. She received her Ph.D. from Vanderbilt where she trained as a cell biologist under Dr. Kathleen Gould and received an NSF graduate fellowship. She developed her planarian model system in the laboratory of Dr. Philip Newmark at the University of Illinois where she received a prestigious Jane Coffin Childs fellowship. Using transcriptomic and genomic approaches, she has identified dozens of genes involved various aspects of nervous system regeneration. She plans to follow up this work to characterize fundamental mechanisms through which neurons and glia are made and organized following injury.
 
#### Dr. Gyorgy Lur, January 26, 2017, 4 PM, 008 Mueller

Dr. Lur uses optical and electrophysiological approaches to study signaling in cortical networks. His long-term goal is to determine how multiple sensory signals are integrated modulated by behavior in the cortex. He received his Ph.D. from the University of Liverpool where he studied calcium signaling in polarized secretory cells. He is currently a postdoctoral fellow in the laboratory of Dr. Michael Higley at Yale University where he has pioneered new methods to combine cellular electrophysiology with 2-Photon imaging to make important new insights into synaptic integration in individual cortical neurons.