---
title: "Values"
---

### Penn State Principles

The Pennsylvania State University is a community dedicated to personal and academic excellence. The Penn State Principles were developed to embody the values that we
hope our students, faculty, staff, administration, and alumni possess. At the same time, the University is strongly committed to freedom of expression. Consequently, these Principles do not constitute University policy and are not intended to interfere in any way with an individual's academic or personal freedoms. We hope, however, that
individuals will voluntarily endorse these common principles, thereby contributing to the traditions and scholarly heritage left by those who preceded them, and will thus
leave Penn State a better place for those who follow.
 
**I will respect the dignity of all individuals within the Penn State community**. The University is committed to creating and maintaining an educational environment that
respects the right of all individuals to participate fully in the community. Actions motivated by hate, prejudice, or intolerance violate this principle. I will not engage in any behaviors that compromise or demean the dignity of individuals or groups, including intimidation, stalking, harassment, discrimination, taunting, ridiculing, insulting, or acts of violence. I will demonstrate respect for others by striving to learn from differences between people, ideas, and opinions and by avoiding behaviors that inhibit the ability of other community members to feel safe or welcome as they pursue their academic goals.
 
**I will practice academic integrity**. Academic integrity is a basic guiding principle for all academic activity at Penn State University, allowing the pursuit of scholarly activity in an open, honest, and responsible manner. In accordance with the University Code of Conduct, I will practice integrity in regard to all academic assignments. I will not engage in or tolerate acts of falsification, misrepresentation or deception because such acts of dishonesty violate the fundamental ethical principles of the University 
community and compromise the worth of work completed by others.
 
**I will demonstrate social and personal responsibility**. The University is a community that promotes learning; any behaviors that are inconsistent with that goal are
unacceptable. Irresponsible behaviors, including alcohol or drug abuse and the use of violence against people or property, undermine the educational climate by 
threatening the physical and mental health of members of the community. I will exercise personal responsibility for my actions and I will make sure that my actions do not 
interfere with the academic and social environment of the University. I will maintain a high standard of behavior by adhering to the Code of Conduct and respecting the 
rights of others.
 
**I will be responsible for my own academic progress and agree to comply with all University policies**. The University allows students to identify and achieve their academic goals by providing the information needed to plan the chosen program of study and the necessary educational opportunities, but students assume final responsibility for course scheduling, program planning, and the successful completion of graduation requirements. I will be responsible for seeking the academic and career information 
needed to meet my educational goals by becoming knowledgeable about the relevant policies, procedures, and rules of the University and academic program, by consulting 
and meeting with my adviser, and by successfully completing all of the requirements for graduation.
 
### Penn State Values

[**Integrity**](http://universityethics.psu.edu/examples-action#integrityexamples): We act with integrity and honesty in accordance with the highest academic, professional, and ethical standards.
 
[**Respect**](http://universityethics.psu.edu/examples-action#respectexamples): We respect and honor the dignity of each person, embrace civil discourse, and foster a diverse and inclusive community.
 
[**Responsibility**](http://universityethics.psu.edu/examples-action#responsibilityexamples): We act responsibly, and we are accountable for our decisions, actions, and their consequences.
 
[**Discovery**](http://universityethics.psu.edu/examples-action#discoveryexamples): We seek and create new knowledge and understanding, and foster creativity and innovation, for the benefit of our communities, society, and the environment.
 
[**Excellence**](http://universityethics.psu.edu/examples-action#excellenceexamples): We strive for excellence in all our endeavors as individuals, an institution, and a leader in higher education.
 
[**Community**](http://universityethics.psu.edu/examples-action#communityexamples: We work together for the betterment of our University, the communities we serve, and the world.