---
title: "exam-3-study-guide"
date: "`r Sys.time()`"
bibliography: bib/bibliography.bib
output:
  ioslides_presentation:
    css: css/ioslides.css
    incremental: no
    transition: default
    widescreen: yes
  pdf_document:
    latex_engine: xelatex
---

## Action

- Monosynaptic stretch reflex
    - Also called "myotatic"
    - Polysynaptic component
- Intrafusal/extrafusal muscle fibers
    - Extrafusal == produce force
    - Intrafusal == take up slack in muscle spindles
- Parkinson's, Huntington's
- Wolpert's ideas about role of brains in movement planning

## Somatosensation

- Functional segregation
    - Different receptors detect different qualities/dimensions
- What information projects to brain fastest & why?
    - Thick axons & thick myelin -> proprioception from muscle spindles
- Similarities to, differences from vision, audition
- Relation between sensitivity, receptor density, receptive field size, and corresponding cortical area.
    - Higher sensitivity == > density, < receptive field size, > cortical area size

## Disorders

- Serotonin/monoamine hypothesis of depression, treatments
- Treatments for bipolar disorder
- Dopamine hypothesis of schizophrenia & alternative

## Emotion

- Plutchik
- Fear, stress circuits
- Reward/happiness circuits
    - Milner & Olds stimulation experiment

## Sleep

- Suprachiasmatic nucleus, melatonin

## Hormones

- Oxytocin
- Cortisol

## Evolution

- Relative brain sizes among mammals

## Neuroanatomy

- Ventricles
- Lobes of the cerebral cortex
- Parts of the brain

## Neurophysiology

- Resting, action potentials
- Postsynaptic potentials, end plate potential (muscle fiber)
- Role of Ca++ in
    - Synaptic communication
    - Muscular contraction

## Next time

- Exam 3

## References {.smaller}
